Repository DataBiosphere/jade-data-repo, pull requests merged in 2020-12, with the labels that each got.

#733 Datarepo helm chart version update: 0.1.28
  .github/workflows/alpha-promotion.yaml
Labels: automerge, datarepo, helm, skip-ci, version-update

#734 Auto merger
  .github/workflows/automerge.yaml
Labels: automerge, skip-ci

#735 Datarepo helm chart version update: 0.1.29
  .github/workflows/alpha-promotion.yaml
Labels: automerge, datarepo, helm, skip-ci, version-update

#739 Datarepo helm chart version update: 0.1.30
  .github/workflows/alpha-promotion.yaml
Labels: automerge, datarepo, helm, skip-ci, version-update

#744 Datarepo helm integraton chart version update
  .github/workflows/int-and-connected-test-run.yml
Labels: automerge, datarepo, helm, version-update

#752 DR-1536: Send alerts for nightly integration tests
  .github/workflows/int-and-connected-test-run.yml
Labels: skip-ci
